### ISSUE TITLE
Model compilation error using rstan 2.8.9 on 64bit Windows

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/rstan#241]
I use the dev version of rstan (rstan 2.8.9, stanHeaders 2.8.9) on 64bit Windows (g++ of Rtools) and get an error during compilation of an arbitrary model, for instance `8schools`:

```
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from C:/Users/Paul/Documents/R/win-library/3.2/rstan/include/rstan/rstaninc.hpp:3:0,
                 from filea7d07bfa4160.cpp:444:
C:/Users/Paul/Documents/R/win-library/3.2/rstan/include/rstan/stan_fit.hpp: In function 'int rstan::{anonymous}::sampler_command(rstan::stan_args&, Model&, Rcpp::List&, const std::vector<long long unsigned int>&, const std::vector<std::basic_string<char> >&, RNG_t&) [with Model = modela7d051ba57ae_0573fc090559f72d423d216e6b63c076_namespace::modela7d051ba57ae_0573fc090559f72d423d216e6b63c076, RNG_t = boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u> >, Rcpp::List = Rcpp::Vector<19>]':
C:/Users/Paul/Documents/R/win-library/3.2/rstan/include/rstan/stan_fit.hpp:1474:7:   instantiated from 'SEXPREC* rstan::stan_fit<Model, RNG_t>::c
In addition: Warning message:
running command 'C:/PROGRA~1/R/R-32~1.2PA/bin/x64/R CMD SHLIB filea7d07bfa4160.cpp 2> filea7d07bfa4160.cpp.err.txt' had status 1 
```

Reinstalling the dev version of rstan (and stanHeaders) couldn't fix it and everything works fine with the CRAN version of rstan. The sessionInfo looks like this:

```
R version 3.2.2 Patched (2015-08-14 r69078)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.8.9   ggplot2_1.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2      digest_0.6.8    MASS_7.3-43      grid_3.2.2       plyr_1.8.3       gtable_0.1.2     stats4_3.2.2     magrittr_1.5     scales_0.3.0    
[11] stringi_1.0-1    reshape2_1.4.1   proto_0.3-10     statmod_1.4.22   tools_3.2.2      stringr_1.0.0    munsell_0.4.2    parallel_3.2.2   abind_1.4-3      inline_0.3.14   
[21] colorspace_1.2-6 gridExtra_2.0.0 
```

If needed, I can post the complete output of the compiler.

**Comment by bgoodri** [comment]
Thanks. The problem was that the git repository uses symlinks to the parts of the submodules that are used by StanHeaders, which are not recognized by Windows. This should be fixed by 54b1e66 but you have to do either `R CMD build` before `R CMD INSTALL` or do `R CMD INSTALL --preclean`.

**Comment by paul-buerkner** [comment]
Thanks. I used to copy the Stan and Math folders into their corresponding directories manually, but your fix makes this alot easier.

I have now downloaded the latest math and stan files (including the cvode library) and installing StanHeader (with --preclean) and rstan again. Unfortunately, the error still occurs while trying to compile a model.

**Comment by paul-buerkner** [comment]
With the new rstan 2.9.0 version, this error no longer occurs.
