### ISSUE TITLE
Compilation error with latest CRAN packages (and R 3.5.2)

### ISSUE THREAD

**Issue by medains** [stan-dev/rstan#666]
#### Summary:
Compilation error with a test execution of rstan after successful package installation.

#### Description:
Initially discovered when installing prophet (see https://github.com/facebook/prophet/issues/1027) with a new host.  Installations on previous versions of packages was successful, but the latest version fails.

#### Reproducible Steps:
With R 3.5.2-2 (Enterprise Linux 7 package) on CentOS 7
```
install.packages('rstan')
library('rstan')
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)
mean(extract(fit)$y)
```

#### Current Output:
```
> library('rstan')
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.18.2, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
> model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
> fit <- stan(model_code=model_code)
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! In file included from /usr/lib64/R/library/BH/include/boost/random/detail/integer_log2.hpp:19:0,
                 from /usr/lib64/R/library/BH/include/boost/random/detail/int_float_pair.hpp:26,
                 from /usr/lib64/R/library/BH/include/boost/random/exponential_distribution.hpp:27,
                 from /usr/lib64/R/library/BH/include/boost/random/gamma_distribution.hpp:25,
                 from /usr/lib64/R/library/StanHeaders/include/stan/math/prim/mat/prob/dirichlet_rng.hpp:5,
                 from /usr/lib64/R/library/StanHeaders/include/stan/math/prim/mat.hpp:292,
                 from /usr/lib64/R/library/StanHeaders/include/stan/math/rev/mat.hpp:12,
                 from /usr/lib64/R/library/StanHeaders/include/stan/math.hpp:4,
                 from /usr/lib64/R/library/StanHeaders/include/src/stan/model/model_header.hpp:4,
                 from file1316ae24e3.cpp:8:
/usr/lib64/R/library/BH/include/boost/
In addition: Warning message:
In system(cmd, intern = !verbose) :
  running command '/usr/lib64/R/bin/R CMD SHLIB file1316ae24e3.cpp 2> file1316ae24e3.cpp.err.txt' had status 1
Error in sink(type = "output") : invalid connection
> 
```

#### Expected Output:
Proper calculation of mean value (should be close to 0)

#### RStan Version:
2.18.2

#### R Version:
3.5.2

#### Operating System:
CentOS 7

### Extra info
```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.18.2          StanHeaders_2.18.1-10 ggplot2_3.2.0        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         magrittr_1.5       munsell_0.5.0      colorspace_1.4-1  
 [5] R6_2.4.0           rlang_0.3.4        tools_3.5.2        parallel_3.5.2    
 [9] pkgbuild_1.0.3     grid_3.5.2         gtable_0.3.0       loo_2.1.0         
[13] cli_1.1.0          withr_2.1.2        matrixStats_0.54.0 lazyeval_0.2.2    
[17] assertthat_0.2.1   tibble_2.1.3       crayon_1.3.4       processx_3.3.1    
[21] gridExtra_2.3      callr_3.2.0        ps_1.3.0           inline_0.3.15     
[25] compiler_3.5.2     pillar_1.4.1       scales_1.0.0       prettyunits_1.0.2 
[29] stats4_3.5.2       pkgconfig_2.0.2   
> 
```

**Comment by wsmolak** [comment]
Hi,

I have the same issue. My environment is slightly different, but we have the same outputs during prophet installation and running the piece of code with rstan.

>sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

**Comment by syntgx** [comment]
Hello, 

Alas, I have exactly the same issue. 

sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

**Comment by ghost** [comment]
Hello, 

No problems to report for me, here:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)
```
and here are all good:
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)
```

**Comment by wsmolak** [comment]
@ode33 so what does it mean? Are RHEL and CentOS not supported?

Works for me when I've downgraded rstan and StanHeaders:
rstan_2.18.1       StanHeaders_2.18.0

**Comment by medains** [comment]
Using verbose=TRUE to see all the errors, the first actual error is:
  /usr/lib64/R/library/StanHeaders/include/stan/math/rev/mat/functor/adj_jac_apply.hpp:31:32: error: ‘std::index_sequence’ has not been declared

This seems to indicate that c++14 is not being correctly applied, my ~/.R/Makevars contains
```
CXX14 = g++ -std=c++1y
CXX14FLAGS = -O3 -Wno-unused-variable -Wno-unused-function -fPIC
```
My understanding is that the "-std=c++1y" should be working, but apparently isn't.
```
# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
```

@wsmolak @syntgx @ode33 : are your Makevars and gcc version similar?

**Comment by wsmolak** [comment]
@medains my Makevars is a bit different

`CXX14FLAGS=-O3 -march=native -mtune=native -fPIC -std=c++11`
`CXX14=g++`

g++ is the same.

I've also tried with clang++ instead of g++ but the same problems occured.
As I stated before problem has gone with downgraded rstan and StanHeaders.

**Comment by cfbeuchel** [comment]
Hi!

I'm having the same problem when trying to fit a model via brms. Downgrading only StanHeaders (to StanHeaders_2.18.0, thx for the tipp @wsmolak) resulted in successful compilation of the model for me.

 My Makevars is the following:

```
CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
CXX14=g++ -std=c++11
```

My session:
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: openSUSE Leap 42.3

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] Biobase_2.42.0        BiocGenerics_0.28.0   evaluate_0.13
 [4] knitr_1.22            rstan_2.18.2          StanHeaders_2.18.1-10
 [7] ggplot2_3.2.0         brms_2.9.3            Rcpp_1.0.1
[10] lmerTest_3.1-0        coda_0.19-2           lme4_1.1-21
[13] Matrix_1.2-17         here_0.1              R.utils_2.9.0
[16] R.oo_1.22.0           R.methodsS3_1.7.1     toolboxH_0.1.30
[19] CarlHelpR_0.0.40      magrittr_1.5          data.table_1.12.2

loaded via a namespace (and not attached):
...more stuff...
```

**Comment by jpzhangvincent** [comment]
I also got the same issue. And tried the downgrading approach but it's still not working. Any thoughts? Thanks!

**Comment by mwmclean** [comment]
My package now works with `CXX_STD = CXX14` in my `Makevars`; I would try that in `.R/Makevars` if you haven't already.
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS
```

**Comment by medains** [comment]
Not fixed for me yet.  I got the same issue with 2.19.2

.R/Makevars
```
CPPFLAGS = -I/usr/include/udunits2
CXX14 = g++ -std=c++1y
CXX14FLAGS = -O3 -Wno-unused-variable -Wno-unused-function -fPIC
CXX_STD = CXX14
```

```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rstan_2.19.2          ggplot2_3.2.0         StanHeaders_2.18.1-10

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         magrittr_1.5       munsell_0.5.0      colorspace_1.4-1  
 [5] R6_2.4.0           rlang_0.4.0        tools_3.5.2        parallel_3.5.2    
 [9] pkgbuild_1.0.3     grid_3.5.2         gtable_0.3.0       loo_2.1.0         
[13] cli_1.1.0          withr_2.1.2        matrixStats_0.54.0 lazyeval_0.2.2    
[17] assertthat_0.2.1   tibble_2.1.3       crayon_1.3.4       processx_3.4.0    
[21] gridExtra_2.3      callr_3.3.0        ps_1.3.0           inline_0.3.15     
[25] compiler_3.5.2     pillar_1.4.2       scales_1.0.0       prettyunits_1.0.2 
[29] stats4_3.5.2       pkgconfig_2.0.2   
```

**Comment by mxf727p** [comment]
Hi all, just want to confirm that downgrade rstan and StanHeaders as suggested by wsmolak solved the exact same issue for me on CentOS 7.

**Comment by yutannihilation** [comment]
Same issue here with rstan 2.19.2 (2.18.2 works, though).

`std::index_sequence` was added to GCC by this commit, and is available only after GCC 4.9.0: https://github.com/gcc-mirror/gcc/commit/d7c3eac64d5f0afad9605646417c4063c82b0333; so, I guess no `Makevars` can make the compile success on CentOS, where the version of GCC is 4.8.5.

This might be a Boost's bug, but it seems C++14 on GCC 4.8.x is not listed in test targets, so I'm not sure if we can expect the fix on their side...

```
GCC, C++0x: 4.4.7
GCC, C++11: 4.7.3, 4.8.5, 4.9.4, 5.4.0, 6.4.0, 7.1.0, 8.0.1
GCC, C++14: 5.4.0, 5.5.0, 6.4.0, 7.1.0, 7.3.0, 8.0.1
GCC, C++17: 7.3.0, 8.0.1
Intel, C++14: 18.0
```

https://www.boost.org/users/history/version_1_69_0.html

**Comment by statwonk** [comment]
The solution in @medains [comment](https://github.com/stan-dev/rstan/issues/666#issuecomment-507274875) helped me compile `rstan` on Ubuntu 14.04 LTS.

To `~/.R/Makevars`, add,

```
CXX14 = g++ -std=c++1y
CXX14FLAGS = -O3 -Wno-unused-variable -Wno-unused-function -fPIC
```

**Comment by tobiasgerstenberg** [comment]
I've tried various versions without success on CentOS 7. 

I get this code to work 

```
install.packages('rstan')
library('rstan')
model_code <- 'parameters {real y;} model {y ~ normal(0,1);}'
fit <- stan(model_code=model_code)
mean(extract(fit)$y)
```

with downgrading `rstan` and `StanHeaders`

```
devtools::install_version("StanHeaders", version = "2.18.0", repos = "http://cran.us.r-project.org")
devtools::install_version("rstan", version = "2.18.1", repos = "http://cran.us.r-project.org")
```

However, it still doesn't work for fitting models with `brms` (which is what I'm hoping to do). 

My current `~/.R/Makevars` is: 

```
CXX14=g++
CXX14FLAGS=-O3 -fPIC
CXX14STD='-std=c++1y'
```

and I've tried many different versions without success. I've also tried downgrading `brms` to 2.8 and 2.7 but still no luck. 

The `brms` code compiles and runs fine locally on my mac. 

Any pointers for what else I could try would be greatly appreciated!

**Comment by bgoodri** [comment]
The default `g++` in RHEL7 is too old. You need at least version 5 and you can get a later version from
https://developers.redhat.com/products/developertoolset/overview
